### ISSUE TITLE
Launch command not found

### ISSUE THREAD

**Issue by AndrewJSchoen** [RoboStack/ros-foxy#19]
On activating the `ros-foxy` environment, the `launch` command is not available by default. As a result,

`ros2 launch ... ...` results in the following error:
```
Failed to load entry point 'launch': Environment variable 'AMENT_PREFIX_PATH' is not set or empty
Traceback (most recent call last):
  File "/Users/me/miniconda3/envs/ros-foxy/bin/ros2", line 8, in <module>
    sys.exit(main())
  File "/Users/me/miniconda3/envs/ros-foxy/lib/python3.8/site-packages/ros2cli/cli.py", line 39, in main
    add_subparsers_on_demand(
  File "/Users/me/miniconda3/envs/ros-foxy/lib/python3.8/site-packages/ros2cli/command/__init__.py", line 236, in add_subparsers_on_demand
    extension = command_extensions[name]
KeyError: 'launch'
```

The full list of commands (on running `ros2`) are:

```
Commands:
  action     Various action related sub-commands
  bag        Various rosbag related sub-commands
  component  Various component related sub-commands
  daemon     Various daemon related sub-commands
  doctor     Check ROS setup and other potential issues
  interface  Show information about ROS interfaces
  lifecycle  Various lifecycle related sub-commands
  multicast  Various multicast related sub-commands
  node       Various node related sub-commands
  param      Various param related sub-commands
  pkg        Various package related sub-commands
  run        Run a package specific executable
  service    Various service related sub-commands
  topic      Various topic related sub-commands
  wtf        Use `wtf` as alias to `doctor`
```

**Comment by Tobias-Fischer** [comment]
This should be fixed in Galactic / Humble.
